# ==============================================================================
# MISSION CONTROL: EXOPLANET KEPLER-A (OOP Edition)
# Python Data & Visualization Workshop - FULL SOLUTION
# ==============================================================================

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.signal import savgol_filter
from scipy.optimize import minimize
from matplotlib.widgets import Slider
import pandas as pd

# pip install "setuptools<70"


class KeplerMission:
    def __init__(self):
        print("Initializing Mission Control...")
        self.time = np.linspace(-10, 10, 500)

        self.flux_clean = None
        self.flux_noisy = None
        self.flux_filtered = None
        self.path = []

    def phase_1_clean_signal(self):
        print("Starting Phase 1...")
        self.flux_clean = np.ones_like(self.time)

        # Create a dip between time -1 and 1
        transit_mask = (self.time > -1) & (self.time < 1)
        self.flux_clean[transit_mask] = 0.42

        # The realistic, smooth Gaussian dip
        depth = 0.02
        width = 0.5
        self.flux_clean = 1.0 - depth * np.exp(-0.5 * (self.time / width) ** 2)

        plt.figure(figsize=(10, 4))
        plt.plot(self.time, self.flux_clean, color='teal', lw=1.5)
        plt.title('Theoretical Exoplanet Transit')
        plt.xlabel('Time (Days)')
        plt.ylabel('Relative Flux')
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.savefig('clean_signal.png', dpi=300, bbox_inches='tight')
        plt.show()

    def phase_2_cosmic_noise(self):
        print("Starting Phase 2...")

        # Inject Gaussian noise and a low-frequency thermal/electronic drift
        noise = np.random.normal(0, 0.0005, len(self.time))
        drift = 0.001 * np.sin(2 * np.pi * self.time / 15)
        self.flux_noisy = self.flux_clean + noise + drift

        # Savitzky-Golay filter (window size must be odd)
        self.flux_filtered = savgol_filter(self.flux_noisy, window_length=41, polyorder=3)

        plt.figure(figsize=(10, 4))
        plt.plot(self.time, self.flux_noisy, color='grey', alpha=0.4, label='Raw Telemetry')
        plt.plot(self.time, self.flux_filtered, color='red', lw=2, label='Savitzky-Golay Filter')

        plt.title('Signal Recovery (Notice the lack of ringing on the smooth dip!)')
        plt.xlabel('Time (Days)')
        plt.ylabel('Relative Flux')
        plt.legend()
        plt.grid(True)
        plt.show()

    # ==========================================================================
    # PHASE 3: Weighing the Cosmos (Linear vs. Log)
    # ==========================================================================
    def phase_3_weigh_cosmos(self):
        print("Starting Phase 3...")

        df = sns.load_dataset('planets').dropna(subset=['orbital_period'])

        # Calculate approximate semi-major axis (AU) assuming 1 Solar Mass host stars
        # Kepler's Third Law: P^2 = a^3 (where P is in years, a is in AU)
        df['semi_major_axis'] = (df['orbital_period'] / 365.25) ** (2 / 3)

        # Drop any potential NaNs generated by the math
        df = df.dropna(subset=['semi_major_axis'])

        # 3. Log-Log Scale Plot (The "Good" Plot)
        plt.figure(figsize=(8, 6))
        # Update the x-axis to be the semi_major_axis!
        sns.scatterplot(data=df, x='semi_major_axis', y='orbital_period', hue='method', alpha=0.7)
        plt.xscale('log')
        plt.yscale('log')
        plt.title("Exoplanet Distribution: Kepler's Third Law (Log-Log Scale)")
        plt.xlabel("Semi-Major Axis (AU)")
        plt.ylabel("Orbital Period (Days)")

        # Fit a 1D polynomial to the log-transformed data
        log_axis = np.log10(df['semi_major_axis'])
        log_per = np.log10(df['orbital_period'])
        slope, intercept = np.polyfit(log_axis, log_per, 1)

        print(f"--> Extracted Power Law Slope: {slope:.3f} (Theory says ~1.5!)")

        # Plot the fit line
        x_fit = np.linspace(df['semi_major_axis'].min(), df['semi_major_axis'].max(), 100)
        y_fit = 10 ** (slope * np.log10(x_fit) + intercept)
        plt.plot(x_fit, y_fit, color='black', lw=2, linestyle='--', label=f'Fit (Slope={slope:.2f})')

        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.tight_layout()
        plt.show()

    # ============================================================
    # HELPER METHODS
    # ============================================================

    def _error_surface(self, vars):
        """
        Rosenbrock function.

        Global minimum:
            f(1,1) = 0
        """
        x, y = vars
        return (1 - x) ** 2 + 100 * (y - x ** 2) ** 2

    def _tracker_callback(self, xk):
        """
        Save optimization trajectory.
        """
        self.path.append(xk.copy())

    # ============================================================
    # FULL PHASE 4 SOLUTION
    # ============================================================

    def phase_4_gravity_well(self):

        print("Starting Phase 4...")
        # Create grid
        x = np.linspace(-3, 3, 400)
        y = np.linspace(-3, 3, 400)

        X, Y = np.meshgrid(x, y)
        Z = self._error_surface((X, Y))

        # Optimization methods
        methods = ['Nelder-Mead', 'Powell', 'CG', 'BFGS','L-BFGS-B']
        x0 = [-2, 2]
        # Store results
        results = {}
        # Plot contour map
        plt.figure(figsize=(12, 9))
        contour = plt.contourf(X,Y,Z,levels=100,cmap='viridis')
        plt.colorbar(contour, label='Error Surface')

        # Run all optimizers
        for method in methods:
            print(f"\nRunning method: {method}")

            # Reset path
            self.path = []

            # Store initial point
            self.path.append(np.array(x0))

            # Run optimizer
            res = minimize(
                self._error_surface,
                x0,
                method=method,
                callback=self._tracker_callback,
                options={
                    'maxiter': 500,
                    'disp': False
                }
            )

            # Save results
            results[method] = res

            # Extract path
            path_x = [p[0] for p in self.path]
            path_y = [p[1] for p in self.path]

            # Plot trajectory
            plt.plot(
                path_x,
                path_y,
                marker='o',
                markersize=3,
                linewidth=1.5,
                label=method
            )

            # Print diagnostics
            print(f"  Final position : {res.x}")
            print(f"  Function value : {res.fun:.6f}")
            print(f"  Iterations     : {res.nit}")
            print(f"  Function evals : {res.nfev}")
            print(f"  Success        : {res.success}")

        # --------------------------------------------------------
        # Plot true minimum
        # --------------------------------------------------------

        plt.plot(
            1,
            1,
            marker='*',
            markersize=18,
            color='red',
            label='True Minimum'
        )

        # --------------------------------------------------------
        # Finalize figure
        # --------------------------------------------------------

        plt.title('Optimization Methods on the Rosenbrock Function')

        plt.xlabel('X Parameter')
        plt.ylabel('Y Parameter')

        plt.legend()

        plt.tight_layout()

        plt.show()

        # --------------------------------------------------------
        # Optional comparison figure
        # --------------------------------------------------------

        methods_names = []
        iterations = []

        for method, res in results.items():
            methods_names.append(method)
            iterations.append(res.nit)

        plt.figure(figsize=(8, 5))

        plt.bar(methods_names, iterations)

        plt.ylabel('Number of Iterations')

        plt.title('Optimizer Iteration Comparison')

        plt.tight_layout()

        plt.show()

    def _calc_dip(self, t, depth, width):
        return 1.0 - depth * np.exp(-0.5 * (t / width) ** 2)

    def phase_5_dashboard(self):
        print("Starting Phase 5...")
        fig, ax = plt.subplots(figsize=(10, 6))
        plt.subplots_adjust(bottom=0.3)

        init_depth = 0.02
        init_width = 2.0

        # Plot initial line
        line, = ax.plot(self.time, self._calc_dip(self.time, init_depth, init_width), lw=2, color='darkred')
        ax.set_ylim(0.9, 1.05)
        ax.set_title("Interactive Kepler Transit Model")
        ax.set_xlabel("Time (Days)")
        ax.set_ylabel("Relative Flux")
        ax.grid(True)

        # Create the sliders
        ax_depth = plt.axes([0.2, 0.15, 0.65, 0.03])
        ax_width = plt.axes([0.2, 0.10, 0.65, 0.03])

        slider_depth = Slider(ax_depth, 'Transit Depth', 0.0, 0.1, valinit=init_depth)
        slider_width = Slider(ax_width, 'Transit Width', 0.1, 5.0, valinit=init_width)

        def update(val):
            # Recalculate using the current values of the sliders
            new_y = self._calc_dip(self.time, slider_depth.val, slider_width.val)
            line.set_ydata(new_y)
            fig.canvas.draw_idle()

        # Attach the callback function
        slider_depth.on_changed(update)
        slider_width.on_changed(update)

        plt.show()


# ==============================================================================
# MAIN EXECUTION
# ==============================================================================
if __name__ == "__main__":
    mission = KeplerMission()
    #mission.phase_1_clean_signal()
    #mission.phase_2_cosmic_noise()
    mission.phase_3_weigh_cosmos()
    # mission.phase_4_gravity_well()
    # mission.phase_5_dashboard()